# Generated by Django 5.2.16 on 2026-07-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airesult',
            name='key_decisions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
